data:
  num_classes: 15
  ignore_label: 255
  training_size: 48095

train:
  seed: 1588147245
  deterministic: False

dataset:
  name: kitti_360
  root: /scratch_net/biwidl303/wboet/datasets/KITTI360/
  num_points: 80000
  voxel_size: 0.05
  radius: 50

num_epochs: 20
batch_size: 2

criterion:
  name: cross_entropy
  ignore_index: 255

optimizer:
  name: sgd
  lr: 2.4e-1
  weight_decay: 1.0e-4
  momentum: 0.9
  nesterov: true

scheduler:
  name: cosine_warmup
